[package]
name = "ether_driver"
version = "0.1.0"
authors = ["Hajime Fukuda <haji.fkd@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2"
